// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5ltkvhy4ZSx4_2fpwT0-IfkxtTFZH_cg',
    appId: '1:912903397115:web:4169181cbdd6ad2e6f1a5e',
    messagingSenderId: '912903397115',
    projectId: 'grindchat-c8a56',
    authDomain: 'grindchat-c8a56.firebaseapp.com',
    storageBucket: 'grindchat-c8a56.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV4JF9u5NJGHaSJayWZViicsXawXpv238',
    appId: '1:912903397115:android:075e56a39fde9a766f1a5e',
    messagingSenderId: '912903397115',
    projectId: 'grindchat-c8a56',
    storageBucket: 'grindchat-c8a56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm97SYriZnpDRFnpefpnt9VCwBvEb-W2A',
    appId: '1:912903397115:ios:4f245495b952116f6f1a5e',
    messagingSenderId: '912903397115',
    projectId: 'grindchat-c8a56',
    storageBucket: 'grindchat-c8a56.firebasestorage.app',
    iosBundleId: 'com.example.code',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm97SYriZnpDRFnpefpnt9VCwBvEb-W2A',
    appId: '1:912903397115:ios:4f245495b952116f6f1a5e',
    messagingSenderId: '912903397115',
    projectId: 'grindchat-c8a56',
    storageBucket: 'grindchat-c8a56.firebasestorage.app',
    iosBundleId: 'com.example.code',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5ltkvhy4ZSx4_2fpwT0-IfkxtTFZH_cg',
    appId: '1:912903397115:web:c564722dc8a8b4436f1a5e',
    messagingSenderId: '912903397115',
    projectId: 'grindchat-c8a56',
    authDomain: 'grindchat-c8a56.firebaseapp.com',
    storageBucket: 'grindchat-c8a56.firebasestorage.app',
  );
}
